In [22]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

# Create the KNN classifier with k=3
knn_model = KNeighborsClassifier(n_neighbors=3)

# Train the model on the training data
knn_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_model.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print correct and wrong predictions
correct_predictions = 0
wrong_predictions = 0
for i in range(len(y_test)):
    if y_test[i] == y_pred[i]:
        print(f"Correct Prediction: Actual: {iris.target_names[y_test[i]]}, Predicted: {iris.target_names[y_pred[i]]}")
        correct_predictions += 1
    else:
        print(f"Wrong Prediction: Actual: {iris.target_names[y_test[i]]}, Predicted: {iris.target_names[y_pred[i]]}")
        wrong_predictions += 1

print("Correct Predictions:", correct_predictions)
print("Wrong Predictions:", wrong_predictions)


Accuracy: 0.9333333333333333
Correct Prediction: Actual: virginica, Predicted: virginica
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: setosa, Predicted: setosa
Correct Prediction: Actual: virginica, Predicted: virginica
Correct Prediction: Actual: setosa, Predicted: setosa
Correct Prediction: Actual: virginica, Predicted: virginica
Correct Prediction: Actual: setosa, Predicted: setosa
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: virginica, Predicted: virginica
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: versicolor, Predicted: versicolor
Correct Prediction: Actual: setosa, Predicted: setosa
Correct Prediction:

In [23]:
from sklearn.datasets import load_iris
dataset=load_iris()
x=dataset.data
y=dataset.target

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [25]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [30]:
from sklearn import metrics
print("conff:\n",metrics.confusion_matrix(y_pred,y_test))
print("accu:",metrics.accuracy_score(y_pred,y_test))
print("pres:",metrics.precision_score(y_pred,y_test,average='weighted'))
print("f1  :",metrics.f1_score(y_pred,y_test,average='weighted'))
print("recal",metrics.recall_score(y_pred,y_test,average='weighted'))

conff:
 [[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]
accu: 0.9666666666666667
pres: 0.9722222222222222
f1  : 0.9675645342312009
recal 0.9666666666666667


In [27]:
rp=0
wp=0
for i in range(len(y_test)):
    if y_test[i] == y_pred[i]:
        print(f"correct pred:- actucal:{dataset.target_names[y_test[i]]} predicted:{dataset.target_names[y_pred[i]]}")
        rp+=1
    else:
        print(f"wrong pred:- actucal:{dataset.target_names[y_test[i]]} predicted:{dataset.target_names[y_pred[i]]}")
        wp+=1

correct pred:- actucal:virginica predicted:virginica
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:setosa predicted:setosa
correct pred:- actucal:virginica predicted:virginica
correct pred:- actucal:setosa predicted:setosa
correct pred:- actucal:virginica predicted:virginica
correct pred:- actucal:setosa predicted:setosa
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
wrong pred:- actucal:virginica predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:setosa predicted:setosa
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:versicolor predicted:versicolor
correct pred:- actucal:setosa predicted:setosa
corr

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'virginica',
       'virginic